/** 기존 프로토타입의 프로필 요약과 내 게시물 목록을 React로 구현한다. */
export default function ProfileView({ cards, categories, onDelete, onUpload }) {
  const mine = cards.filter((card) => card.isMyUpload);
  const votes = mine.reduce((sum, card) => sum + card.yesVotes + card.noVotes, 0);
  const yes = mine.reduce((sum, card) => sum + card.yesVotes, 0);
  const approval = votes ? Math.round((yes / votes) * 100) : 0;
  return <section className="w-full pb-3 pt-1">
    <article className="mb-3.5 rounded-2xl border border-surface-container-high bg-surface-container p-4"><div className="flex items-center gap-3.5"><div className="relative"><img src={cards[0]?.imageUrl} alt="내 프로필" className="h-14 w-14 rounded-full border-2 border-cyan-glow object-cover" /><span className="absolute bottom-0 right-0 flex h-3.5 w-3.5 items-center justify-center rounded-full border-2 border-background bg-cyan-glow"><span className="material-symbols-outlined text-[8px] font-bold text-black">check</span></span></div><div className="flex-1"><h1 className="flex items-center gap-1.5 font-headline text-base font-bold text-white">@career_mode <span className="material-symbols-outlined text-sm text-cyan-glow">verified</span></h1><p className="text-[11px] text-slate-400">비즈니스 &amp; 프로페셔널 이미지 분석 중</p><div className="mt-1 flex items-center gap-1.5"><span className="rounded border border-primary-container/40 bg-primary-container/20 px-1.5 py-0.5 font-mono text-[9px] text-cyan-glow">PRO TIER</span><span className="font-mono text-[10px] text-slate-400">xCubus Score: <strong className="text-white">94.6</strong></span></div></div></div><div className="mt-3 grid grid-cols-3 gap-2 border-t border-surface-container-high pt-3"><Metric value={mine.length} label="내 업로드" /><Metric value={votes.toLocaleString()} label="받은 투표" color="text-cyan-glow" /><Metric value={`${approval}%`} label="평균 호감도" color="text-emerald-400" /></div></article>
    <div className="mb-2.5 flex items-center justify-between"><h2 className="font-headline text-sm font-bold text-white">내가 업로드한 사진 분석</h2><button type="button" onClick={onUpload} className="flex items-center gap-0.5 text-xs font-bold text-cyan-glow"><span className="material-symbols-outlined text-sm">add</span>새로 업로드</button></div>
    <div className="flex flex-col gap-2.5">{mine.length ? mine.map((card) => <PostRow key={card.id} card={card} category={categories[card.category]} onDelete={() => onDelete(card.id)} />) : <p className="rounded-xl border border-surface-container-high bg-surface-container-low p-6 text-center text-xs text-slate-400">아직 업로드한 사진이 없습니다.</p>}</div>
  </section>;
}

function Metric({ value, label, color = 'text-white' }) { return <div className="rounded-xl bg-surface-container-low p-2 text-center"><strong className={`block font-headline text-base font-extrabold ${color}`}>{value}</strong><span className="font-mono text-[9px] uppercase text-slate-400">{label}</span></div>; }
function PostRow({ card, category, onDelete }) { const total = card.yesVotes + card.noVotes; const yesRate = Math.round((card.yesVotes / Math.max(total, 1)) * 100); const noRate = 100 - yesRate; return <article className="flex items-center gap-3 rounded-2xl border border-surface-container-high bg-surface-container p-2.5"><Media card={card} /><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2 text-[10px]"><span style={{ color: category.color }}>{category.label}</span><span className="truncate text-slate-400">@{card.author}</span></div><strong className="mt-1 block truncate font-headline text-xs text-white">{card.question.replace('\n', ' ')}</strong><div className="mt-1.5"><div className="mb-1 flex items-center justify-between font-mono text-[9px]"><span style={{ color: category.color }}>호감 {yesRate}%</span><span className="text-rose-400">비호감 {noRate}%</span></div><div className="flex h-1.5 overflow-hidden rounded-full bg-slate-800"><span style={{ width: `${yesRate}%`, backgroundColor: category.color }} /><span className="bg-rose-500/80" style={{ width: `${noRate}%` }} /></div></div><small className="mt-1 block text-[10px] text-slate-500">유효 투표 {total.toLocaleString()}표</small></div><button type="button" onClick={onDelete} className="text-xs font-bold text-rose-400">삭제</button></article>; }
function Media({ card }) { return card.mediaType === 'video' ? <video className="h-14 w-14 shrink-0 rounded-xl object-cover" src={card.imageUrl} muted playsInline /> : <img className="h-14 w-14 shrink-0 rounded-xl object-cover" src={card.imageUrl} alt="" />; }
