import { useEffect, useMemo, useState } from 'react';
import { Dialog, DialogClose, DialogContent } from '../../components/ui/Dialog.jsx';
import SurfaceCard from '../../components/ui/SurfaceCard.jsx';

/** 정의: 카테고리별 호감도 정렬과 카드 상세 레이어 미리보기를 제공하는 랭킹 화면이다. */
export default function RankingView({ cards, categories }) {
  const [filter, setFilter] = useState('ALL');
  const [ascending, setAscending] = useState(false);
  const [previewCard, setPreviewCard] = useState(null);
  const [page, setPage] = useState(0);
  const sortColor = filter === 'ALL' ? '#735c00' : categories[filter].color;
  const ranked = useMemo(() => cards.filter((card) => filter === 'ALL' || card.category === filter).sort((a, b) => (ascending ? 1 : -1) * (rankingScore(a) - rankingScore(b))), [cards, filter, ascending]);
  const rankingPool = useMemo(() => ranked.length ? Array.from({ length: 100 }, (_, index) => ({ ...ranked[index % ranked.length], id: `${ranked[index % ranked.length].id}-rank-${index + 1}` })) : [], [ranked]);
  const pageCards = rankingPool.slice(page * 10, page * 10 + 10);
  useEffect(() => setPage(0), [filter, ascending]);
  return <section className="editorial-ranking w-full pb-3 pt-1">
    <div className="mb-3 flex items-center justify-between gap-3 py-1"><p className="flex min-w-0 items-center gap-1.5 text-[13px] font-semibold text-white"><span className="material-symbols-outlined shrink-0 text-[17px]" style={{ color: sortColor }}>emoji_events</span>가장 많은 공감을 받은 오늘의 룩을 살펴보세요.</p><button type="button" onClick={() => setAscending((value) => !value)} aria-label={ascending ? '호감도 높은 순으로 정렬' : '호감도 낮은 순으로 정렬'} title={ascending ? '호감도 낮은 순' : '호감도 높은 순'} style={{ color: sortColor, borderColor: `${sortColor}66`, backgroundColor: `${sortColor}12` }} className="relative flex h-8 w-8 shrink-0 items-center justify-center rounded-full border"><span className="material-symbols-outlined text-[16px]">thumb_up</span><span className="material-symbols-outlined absolute -right-0.5 -top-0.5 rounded-full bg-[#f9f7f2] text-[12px]" style={{ color: sortColor }}>{ascending ? 'arrow_upward' : 'arrow_downward'}</span></button></div>
    <div className="no-scrollbar mb-2 flex gap-1.5 overflow-x-auto pb-1"><FilterButton active={filter === 'ALL'} onClick={() => setFilter('ALL')} label="전체 TOP" />{Object.entries(categories).map(([id, item]) => <FilterButton key={id} active={filter === id} onClick={() => setFilter(id)} label={item.label} color={item.color} />)}</div>
    <ol className="flex flex-col gap-1.5">{pageCards.map((card, index) => { const rank = page * 10 + index + 1; const isAge = card.evaluationType === 'NUMERIC_AGE'; const total = isAge ? card.ageVoteCount : card.yesVotes + card.noVotes; const rate = Math.round(approval(card) * 100); const noRate = 100 - rate; const color = categories[card.category]?.color ?? '#735c00'; return <li key={card.id}><SurfaceCard as="button" type="button" onClick={() => setPreviewCard(card)} className="flex w-full items-center gap-2.5 px-2.5 py-1.5 text-left transition-colors hover:border-[#c5a059]/70"><span className="w-5 text-center font-headline text-base font-bold" style={{ color }}>{rank}</span><RankMedia card={card} /><span className="min-w-0 flex-1"><span className="flex items-center justify-between gap-2 text-[9px]"><em className="not-italic" style={{ color }}>{categories[card.category]?.label}</em><strong className="truncate text-slate-300">@{card.author}</strong></span><strong className="block truncate font-headline text-[13px] text-white">{card.question.replace('\n', ' ')}</strong>{isAge ? <div className="mt-0.5 flex items-end justify-between"><span className="font-mono text-[9px]" style={{ color }}>평균 예상 {card.ageEstimate.toFixed(1)}세</span><span className="text-[8px] text-slate-500">주관적 첫인상</span></div> : <div className="mt-0.5"><div className="flex items-center justify-between font-mono text-[8px]"><span style={{ color }}>호감 {rate}%</span><span className="text-[#9b5c55]">비호감 {noRate}%</span></div><div className="flex h-1 overflow-hidden rounded-full bg-[#e4e2dd]"><span style={{ width: `${rate}%`, backgroundColor: color }} /><span className="bg-[#b6847c]" style={{ width: `${noRate}%` }} /></div></div>}<small className="block text-[9px] text-slate-500">유효 평가 {total.toLocaleString()}명</small></span></SurfaceCard></li>; })}</ol>
    <nav className="mt-2 flex items-center justify-center gap-2" aria-label="랭킹 페이지"><button type="button" onClick={() => setPage((value) => Math.max(0, value - 1))} disabled={page === 0} aria-label="이전 10위" className="flex h-7 w-7 items-center justify-center rounded-full border border-[#c4c6cd] text-[#44474c] disabled:opacity-30"><span className="material-symbols-outlined text-[15px]">chevron_left</span></button><span className="min-w-14 text-center font-mono text-[10px] text-slate-400">{page * 10 + 1}–{page * 10 + pageCards.length} / 100</span><button type="button" onClick={() => setPage((value) => Math.min(9, value + 1))} disabled={page === 9} aria-label="다음 10위" className="flex h-7 w-7 items-center justify-center rounded-full border border-[#c4c6cd] text-[#44474c] disabled:opacity-30"><span className="material-symbols-outlined text-[15px]">chevron_right</span></button></nav>
    {previewCard && <RankingPreview card={previewCard} category={categories[previewCard.category]} onClose={() => setPreviewCard(null)} />}
  </section>;
}

/** 정의: 총 투표 수 0에도 안전하게 동작하는 카드 긍정률 계산기다. */
function approval(card) { return (card.yesVotes ?? 0) / Math.max((card.yesVotes ?? 0) + (card.noVotes ?? 0), 1); }
/** 정의: 서로 다른 평가 유형을 랭킹에서 안전하게 정렬하기 위한 점수다. */
function rankingScore(card) { return card.evaluationType === 'NUMERIC_AGE' ? card.ageVoteCount ?? 0 : approval(card); }
/** 정의: 선택 상태와 카테고리 색상을 표현하는 랭킹 필터 버튼이다. */
function FilterButton({ active, onClick, label, color = '#735c00' }) { return <button type="button" onClick={onClick} className="whitespace-nowrap rounded-full border px-3 py-1 font-mono text-xs transition-all" style={active ? { color, borderColor: color, backgroundColor: `${color}1a`, fontWeight: 700 } : { color: '#44474c', borderColor: '#c4c6cd', backgroundColor: '#ffffff' }}>{label}</button>; }
/** 정의: 랭킹 목록의 썸네일 미디어를 사진·동영상 공통 크기로 표시한다. */
function RankMedia({ card }) { return card.mediaType === 'video' ? <video className="h-11 w-11 shrink-0 rounded-md object-cover" src={card.imageUrl} muted playsInline /> : <img className="h-11 w-11 shrink-0 rounded-md object-cover" src={card.imageUrl} alt="" />; }
/** 정의: 랭킹 카드의 원본 미디어와 핵심 지표를 레이어로 확인하는 상세 미리보기다. */
function RankingPreview({ card, category, onClose }) { const isAge = card.evaluationType === 'NUMERIC_AGE'; const total = isAge ? card.ageVoteCount : card.yesVotes + card.noVotes; const rate = Math.round(approval(card) * 100); return <Dialog open onOpenChange={(open) => { if (!open) onClose(); }}><DialogContent aria-label="랭킹 카드 미리보기"><article className="relative w-full max-w-sm overflow-hidden rounded-lg border border-[#e4e2dd] bg-white shadow-xl"><DialogClose asChild><button type="button" aria-label="미리보기 닫기" className="absolute right-3 top-3 z-10 flex h-8 w-8 items-center justify-center rounded-full border border-white/50 bg-white/80 text-[#1b1c19] shadow-sm"><span className="material-symbols-outlined text-lg">close</span></button></DialogClose>{card.mediaType === 'video' ? <video className="aspect-[4/5] w-full object-cover" src={card.imageUrl} controls autoPlay playsInline /> : <img className="aspect-[4/5] w-full object-cover" src={card.imageUrl} alt={`${card.author}의 미리보기`} />}<div className="p-4"><div className="flex items-center justify-between text-xs"><span className="font-mono font-bold" style={{ color: category.color }}>{category.label}</span><span className="text-slate-400">@{card.author}</span></div><h2 className="mt-2 whitespace-pre-line font-headline text-lg font-bold leading-snug text-white">{card.question}</h2><p className="mt-1 text-xs text-slate-400">{card.subtext}</p><div className="mt-4 flex items-center justify-between border-t border-surface-container-high pt-3"><span className="font-mono text-xs text-slate-400">유효 평가 {total.toLocaleString()}명</span><strong className="font-headline text-lg" style={{ color: category.color }}>{isAge ? `평균 예상 ${card.ageEstimate.toFixed(1)}세` : `호감도 ${rate}%`}</strong></div></div></article></DialogContent></Dialog>; }
