import { useMemo, useState } from 'react';

/** 기존 프로토타입의 랭킹 필터와 카드 상세 미리보기를 React로 구현한다. */
export default function RankingView({ cards, categories }) {
  const [filter, setFilter] = useState('ALL');
  const [ascending, setAscending] = useState(false);
  const [previewCard, setPreviewCard] = useState(null);
  const sortColor = filter === 'ALL' ? '#00f0ff' : categories[filter].color;
  const ranked = useMemo(() => cards.filter((card) => filter === 'ALL' || card.category === filter).sort((a, b) => (ascending ? 1 : -1) * (approval(a) - approval(b))), [cards, filter, ascending]);
  return <section className="w-full pb-3 pt-1">
    <div className="mb-3.5 flex items-start justify-between"><div><span className="font-mono text-[11px] font-semibold uppercase tracking-widest text-cyan-glow">Intelligence Leaderboard</span><h1 className="font-headline text-xl font-bold text-white">FirstLook 랭킹</h1><p className="mt-0.5 text-xs text-slate-400">가장 높은 호감도와 신뢰도 점수를 기록한 베스트 룩</p></div><button type="button" onClick={() => setAscending((value) => !value)} aria-label={ascending ? '호감도 높은 순으로 정렬' : '호감도 낮은 순으로 정렬'} title={ascending ? '호감도 낮은 순' : '호감도 높은 순'} style={{ color: sortColor, borderColor: `${sortColor}66`, backgroundColor: `${sortColor}1a` }} className="relative mt-1 flex h-8 w-8 items-center justify-center rounded-full border"><span className="material-symbols-outlined text-[16px]">thumb_up</span><span className="material-symbols-outlined absolute -right-0.5 -top-0.5 rounded-full bg-[#051424] text-[12px]" style={{ color: sortColor }}>{ascending ? 'arrow_upward' : 'arrow_downward'}</span></button></div>
    <div className="no-scrollbar mb-2.5 flex gap-1.5 overflow-x-auto pb-2"><FilterButton active={filter === 'ALL'} onClick={() => setFilter('ALL')} label="전체 TOP" />{Object.entries(categories).map(([id, item]) => <FilterButton key={id} active={filter === id} onClick={() => setFilter(id)} label={item.label} color={item.color} />)}</div>
    <ol className="flex flex-col gap-2.5">{ranked.map((card, index) => { const total = card.yesVotes + card.noVotes; const rate = Math.round(approval(card) * 100); const color = categories[card.category]?.color ?? '#00f0ff'; return <li key={card.id}><button type="button" onClick={() => setPreviewCard(card)} className="flex w-full items-center gap-3.5 rounded-2xl border border-surface-container-high bg-surface-container p-3 text-left transition-colors hover:border-cyan-glow/40"><span className="w-5 text-center font-headline text-base font-extrabold" style={{ color }}>{index + 1}</span><RankMedia card={card} /><span className="min-w-0 flex-1"><span className="mb-1 flex items-center justify-between gap-2 text-[10px]"><em className="not-italic" style={{ color }}>{categories[card.category]?.label}</em><strong className="truncate text-slate-300">@{card.author}</strong></span><strong className="block truncate font-headline text-xs text-white">{card.question.replace('\n', ' ')}</strong><small className="mt-1 block text-[10px] text-slate-500">유효 투표 {total.toLocaleString()}표</small></span><b className="font-mono text-sm" style={{ color }}>{rate}%</b></button></li>; })}</ol>
    {previewCard && <RankingPreview card={previewCard} category={categories[previewCard.category]} onClose={() => setPreviewCard(null)} />}
  </section>;
}

function approval(card) { return card.yesVotes / Math.max(card.yesVotes + card.noVotes, 1); }
function FilterButton({ active, onClick, label, color = '#00f0ff' }) { return <button type="button" onClick={onClick} className="whitespace-nowrap rounded-full border px-3 py-1 font-mono text-xs transition-all" style={active ? { color, borderColor: color, backgroundColor: `${color}26`, fontWeight: 700 } : { color: '#94a3b8', borderColor: '#222a3d', backgroundColor: '#171f33' }}>{label}</button>; }
function RankMedia({ card }) { return card.mediaType === 'video' ? <video className="h-14 w-14 shrink-0 rounded-xl object-cover" src={card.imageUrl} muted playsInline /> : <img className="h-14 w-14 shrink-0 rounded-xl object-cover" src={card.imageUrl} alt="" />; }
function RankingPreview({ card, category, onClose }) { const total = card.yesVotes + card.noVotes; const rate = Math.round(approval(card) * 100); return <div role="dialog" aria-modal="true" aria-label="랭킹 카드 미리보기" onClick={onClose} className="fixed inset-0 z-[70] flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm"><article onClick={(event) => event.stopPropagation()} className="relative w-full max-w-sm overflow-hidden rounded-2xl border border-white/15 bg-[#071625] shadow-2xl"><button type="button" onClick={onClose} aria-label="미리보기 닫기" className="absolute right-3 top-3 z-10 flex h-8 w-8 items-center justify-center rounded-full border border-white/20 bg-black/55 text-white"><span className="material-symbols-outlined text-lg">close</span></button>{card.mediaType === 'video' ? <video className="aspect-[4/5] w-full object-cover" src={card.imageUrl} controls autoPlay playsInline /> : <img className="aspect-[4/5] w-full object-cover" src={card.imageUrl} alt={`${card.author}의 미리보기`} />}<div className="p-4"><div className="flex items-center justify-between text-xs"><span className="font-mono font-bold" style={{ color: category.color }}>{category.label}</span><span className="text-slate-400">@{card.author}</span></div><h2 className="mt-2 whitespace-pre-line font-headline text-lg font-bold leading-snug text-white">{card.question}</h2><p className="mt-1 text-xs text-slate-400">{card.subtext}</p><div className="mt-4 flex items-center justify-between border-t border-surface-container-high pt-3"><span className="font-mono text-xs text-slate-400">유효 투표 {total.toLocaleString()}표</span><strong className="font-headline text-lg" style={{ color: category.color }}>호감도 {rate}%</strong></div></div></article></div>; }
